Repository w3c/webrtc-pc, pull requests merged in 2018-05, with the labels that each got.

#1864 Fix typo s/sdpCauseCode/sctpCauseCode/
  webrtc.html
Labels: Editorial

#1854 Define the reference clock used for RTCRtpContributingSource.timestamp
  webrtc.html
Labels: Editors can integrate, Needs submitter action

#1860 Add sender.setStreams() method to update stream associations.
  webrtc.html
Labels: Editors can integrate

#1862 Trim [[SendEncodings]] down to what user agent supports.
  webrtc.html
Labels: Editors can integrate
