Repository w3c/webrtc-pc, pull requests merged in 2018-06, with the labels that each got.

#1822 Data channel closing procedure
  webrtc.html
Labels: Needs submitter action

#1886 Fire signalingstatechange later at end of SLD/SRD algorithm like other events
  webrtc.html
Labels: Needs Test

#1906 Fix link to timeOrigin
  webrtc.html
Labels: Editorial

#1911 Adding note about the relationship between tracks of senders/receivers.
  webrtc.html
Labels: Editors can integrate
