Repository w3c/webrtc-pc, pull requests merged in 2019-10, with the labels that each got.

#2222 Add initialization of DataChannelId on connection
  webrtc.html
Labels: Editors can integrate, Needs submitter action

#2320 Mark ptime as at risk
  webrtc.html
Labels: Editors can integrate

#2304 Make RTCStats.id unpredictable
  webrtc.html
Labels: Editors can integrate

#2321 Clarify when 'failed' is not a terminal RTCIceTransportState.
  webrtc.html
Labels: Editors can integrate

#2322 Clarify the rules for filtering and split hostCandidate in address and port
  webrtc.html
Labels: Needs Test

#2317 Add text describing *Description consistency
  webrtc.html
Labels: Editors can integrate

#2329 Move data-channel-failure event to end of SRD with the other sync events
  webrtc.html
Labels: Editors can integrate

#2336 Be explicit about no ICE event on close
  webrtc.html
Labels: Editorial

#2340 Define remote track settings, constraints not applicable
  webrtc.html
Labels: Editors can integrate, Needs Test

#2318 Remove onstatsended event
  webrtc.html
Labels: Editors can integrate
