Repository w3c/webrtc-pc, pull requests merged in 2019-11, with the labels that each got.

#2331 Introduce [[IceRole]] internal slot
  webrtc.html
Labels: Editors can integrate

#2351 Remove codecPayloadType, dtx, ptime and maxFramerate from parameters
  webrtc.html
Labels: Editors can integrate

#2353 Remove RTCRtcpMuxPolicy::negotiate and rtcpTransport
  webrtc.html
Labels: Editors can integrate

#2342 Remove Priority from Sender and Datachannel
  webrtc.html
Labels: Please take a look

#2359 Move former editors to separate entry
  webrtc.js
Labels: Editorial

#2361 Remove maxFramerate (to be moved to extension spec)
  webrtc.html
Labels: Editors can integrate

#2362 Remove OAuth (to be moved to an extension spec)
  webrtc.html
Labels: Editors can integrate

#2365 Remove [[WEBIDL-1]] reference in favor of [[WEBIDL]]
  webrtc.html
Labels: Please take a look

#2366 Update Mandatory stats to match refactoring
  webrtc.html
Labels: Please take a look

#2372 Revert transports on rollback
  webrtc.html
Labels: Please take a look

#2373 Revert [[ReceiveCodecs]] on rollback
  webrtc.html
Labels: Needs Test, Please take a look

#2381 Remove getDefaultIceServers reference from "at risk" section
  webrtc.html
Labels: Please take a look

#2385 Note that getSynchronizationSources works without sinks
  webrtc.html
Labels: Editors can integrate, Needs Test

#2383 Remove RTCRtpReceiveParameters.encodings
  webrtc.html
Labels: Editors can integrate, Needs Test

#2380 Mark RTCError attributes "at risk"
  webrtc.html
Labels: Editors can integrate

#2375 Construct RTCErrors with name 'OperationError' instead of 'RTCError'
  webrtc.html
Labels: Needs submitter action

#2377 Set receiver.[[ReceiveCodecs]] on all descriptions.
  webrtc.html
Labels: Editors can integrate, Needs Test
