Repository w3c/webrtc-pc, pull requests merged in 2019-02, with the labels that each got.

#2064 Add description of DTLS transport error handling.
  webrtc.html
Labels: Editors can integrate, Needs Test

#2090 Indicate where idp- errors are used.
  webrtc.html
Labels: Editors can integrate

#2098 Fix duplicate ids for overloaded RTCDataChannel.send
  webrtc.js
Labels: Editorial

#2081 Clarifying how the simulcast envelope is created.
  webrtc.html
Labels: Editors can integrate, Simulcast

#2107 Block replaceTrack on pc.close() like the others, not tc.stop().
  webrtc.html
Labels: Needs Test
