Repository w3c/webrtc-pc, pull requests merged in 2019-07, with the labels that each got.

#2169 Add pc.restartIce() method.
  webrtc.html
Labels: July 2019 Virtual Interim, Needs Test

#2209 Read [[LastCreatedOffer/Answer]] at the right time in SLD
  webrtc.html
Labels: Editors can integrate

#2212 Add implicit rollback to setRemoteDescription(description)
  webrtc.html
Labels: July 2019 Virtual Interim, Needs Test

#2223 Add the "closing" event to datachannel
  webrtc.html
Labels: Needs Test

#2232 Fix inconsistent WebIDL. Reformat to follow de facto code style of WebIDL,HTML,DOM. (editorial)
  webrtc.html
Labels: Editors can integrate, Needs submitter action

#2203 Ensure icecandidate events happen after SLD success.
  webrtc.html
Labels: Editors can integrate, Needs Test

#2234 Support setLocalDescription() without arguments.
  webrtc.html
Labels: Needs Test

#2237 Cannot roll back pranswer. Throw InvalidStateError.
  webrtc.html
Labels: Editors can integrate, Needs Test
