Repository w3c/webrtc-pc, pull requests merged in 2019-12, with the labels that each got.

#2376 Note that ICE transport state can go to completed
  webrtc.html
Labels: Editors can integrate

#2328 Add accessibility considerations regarding real-time text
  webrtc.html
Labels: Please take a look

#2333 Strengthen secure module language around keying material & add security note
  webrtc.html
Labels: Please take a look

#2384 Add explicit "rollback" steps
  webrtc.html
Labels: Needs Test, Please take a look

#2391 Add a couple of identity hooks (editorial)
  webrtc.html
Labels: Editorial

#2392 Make getParameters() idempotent + queue task to clear [[LastReturnedParameters]]
  webrtc.html
Labels: Needs Test

#2393 Add Perfect Negotiation example.
  webrtc.html
Labels: Editorial, Needs Test

#2395 Do not send audio when track is disabled
  webrtc.html
Labels: Needs Test

#2389 Fix a few references
  webrtc.html
Labels: Editorial

#2399 Removing degradationPreference
  webrtc.html
Labels: Editors can integrate

#2390 Remove constructs and steps related to identity handling
  webrtc.html
Labels: Editors can integrate

#2402 Reject RID renegotiation
  webrtc.html
Labels: Discuss at editor's meeting, Needs Test

#2403 Use proper WHATWG references for webmessaging, xhr, web sockets
  webrtc.html
Labels: Editorial

#2405 Chain the firing of negotiationneeded.
  webrtc.html
Labels: Needs Test

#2406 Fix race in perfect negotiation example.
  webrtc.html
Labels: Editorial, Needs Test

#2409 Remove one now-redundant mention of rollback (editorial)
  webrtc.html
Labels: Editorial

#2400 Fire statechange, iceconnectionstatechange & connectionstatechange events in same task.
  webrtc.html
Labels: Editors can integrate, Needs Test

#2401 Specify that SCTP transport goes to "closed" on DTLS close
  webrtc.html
Labels: Editors can integrate, Needs Test

#2407 Prepare for CR publication
  W3CTRMANIFEST
  respec-w3c-common.js
  webrtc.html
  webrtc.js
Labels: Editorial

#2417 Use ReSpec shortcut for internal and external references
  webrtc.html
  webrtc.js
Labels: Editorial, Editors can integrate

#2420 Editorial fixes
  webrtc.html
Labels: Editorial
