Repository w3c/webrtc-pc, pull requests merged in 2019-04, with the labels that each got.

#2140 s/LastOffer/LastCreateOffer/ ditto answer.
  webrtc.html
Labels: Editors can integrate

#2155 Attach simulcast offer sendEncodings to suitable (addTrack) transceiver.
  webrtc.html
Labels: Needs Test

#2156 Add in-line references to relevant test cases
  README.md
  webrtc.html
Labels: Editorial, Editors can integrate

#2160 Remove stopped transceivers after negotiation
  webrtc.html
Labels: Editors can integrate, Needs Test
