Repository w3c/webrtc-pc, pull requests merged in 2019-01, with the labels that each got.

#2048 Define which m= section is offerer tagged.
  webrtc.html
Labels: Editors can integrate, Needs Test

#2050 Stop bundled transceivers when the offerer tagged is stopped.
  webrtc.html
Labels: Editors can integrate, Needs Test

#2075 Simulcast SDP clarifications
  webrtc.html
Labels: Editors can integrate, Needs Test, Simulcast

#2069 setCodecPreferences and RTX / RED / FEC codecs
  webrtc.html
Labels: Editors can integrate, Needs Test

#2071 Describe how RIDs are added to a media section
  webrtc.html
Labels: Needs Test, Simulcast

#2085 Effect of RTCRtpSendParameters on Simulcast
  webrtc.html
Labels: Simulcast
