Repository w3c/webrtc-pc, pull requests merged in 2020-07, with the labels that each got.

#2548 Reorganize list of MTI stats based on their RTCStatsType
  webrtc.html
Labels: Editorial

#2550 Fix url to download respec
  .github/workflows/update-respec.yml
Labels: Editorial

#2555 Stop transports that are no longer used and fire events.
  webrtc.html
Labels: Needs Test

#2540 Add language to block bad candidates.
  webrtc.html
Labels: Editors can integrate

#2560 editorial: s/signalling/signaling/
  webrtc.html
Labels: Editorial
