Repository w3c/webrtc-pc, pull requests merged in 2020-03, with the labels that each got.

#2488 Have update negotiation-needed steps return a promise
  webrtc.html
Labels: Editorial

#2473 Annotating section 5
  webrtc.html
Labels: Editors can integrate

#2491 Add missing onicecandidate & comments to perfect negotiation example.
  webrtc.html
Labels: Editorial

#2492 Refactor collision example to avoid assignment in if statement.
  webrtc.html
Labels: Editorial, Editors can integrate
