Repository w3c/webrtc-pc, pull requests merged in 2020-01, with the labels that each got.

#2431 Upgrade to Respec 25.0.2
  respec-w3c-common.js
  webrtc.html
  webrtc.js
Labels: Editorial

#2416 Reinstate credential attribute in RTCIceServer
  webrtc.html
Labels: Editors can integrate

#2423 Various editorial clean up
  webrtc.html
Labels: Editorial

#2428 Remove vestiges of httpRequestStatusCode (editorial)
  webrtc.html
Labels: Editorial

#2435 Remove unneeded fallback state 'new' for create an RTCSctpTransport
  webrtc.html
Labels: Editorial

#2436 Provide useful anchors for IDL definitions
  webrtc.html
Labels: Editorial

#2439 Add more ReSpec auto-links
  webrtc.html
  webrtc.js
Labels: Editorial

#2440 Update test annotations
  respec-w3c-common.js
  webrtc.html
  webrtc.js
Labels: Editorial

#2429 Touch up examples.
  webrtc.html
Labels: Editorial, Editors can integrate

#2449 RTCPeerConnectionIceErrorEventInit with address and port
  webrtc.html
Labels: Please take a look

#2444 Handle ICE state and candidate pair changes in the same task
  webrtc.html
Labels: Needs Test

#2447 Fix RTCPeerConnectionState references to dependent states
  webrtc.html
Labels: Editorial

#2450 Make 4.4.1 Operation's NOTE say 'signaling state'
  webrtc.html
Labels: Please take a look

#2453 fix stun/turn uri rfc references
  webrtc.html
Labels: Editorial

#2445 Add note explaining addTrack/addTransceiver-created transceivers
  webrtc.html
Labels: Editors can integrate

#2434 Fire closing event
  webrtc.html
Labels: Editors can integrate

#2452 Clarify that removed codec need not be listed
  webrtc.html
Labels: Editorial, Editors can integrate
