Repository w3c/webrtc-pc, pull requests merged in 2021-12, with the labels that each got.

#2691 Fix setConfiguration default value handling to match implementations.
  webrtc.html
Labels: Editors can integrate

#2702 Add test annotations for candidates arriving after SLD
  webrtc.html
Labels: Editors can integrate, Editorial

#2700 Convert generateCertificate argument to DOMHighResTimeStamp
  webrtc.html
Labels: Editors can integrate

#2703 Update to latest ReSpec version
  respec-w3c-common.js
Labels: Editorial

#2705 Update to ReSpec version 28.0.7
  respec-w3c-common.js
Labels: Editorial

#2704 new->failed transition & wait for PAC timer if > 0 local candidates
  images/icetransportstate.svg
  webrtc.html
Labels: Needs Test
