Repository w3c/webrtc-pc, pull requests merged in 2022-07, with the labels that each got.

#2750 Update to ReSpec version 32.1.10
  respec-w3c-common.js
Labels: Editorial, repo-management

#2749 Use conventional class for algorithm markup
  webrtc.html
Labels: Editorial

#2756 Update to ReSpec version 32.2.0
  respec-w3c-common.js
Labels: Editorial, repo-management

#2759 Revert #2033.
  webrtc.html
Labels: Needs Test
