Repository w3c/webrtc-pc, pull requests merged in 2022-10, with the labels that each got.

#2713 Document substantive changes since Rec as candidate amendments
  amendments.json
  amendments.md
  base-rec.html
  diff.js
  webrtc.css
  webrtc.html
  webrtc.js
Labels: Editors can integrate

#2776 Update to ReSpec version 32.2.5
  respec-w3c-common.js
  webrtc.html
  webrtc.js
Labels: Editorial, repo-management

#2774 TypeError unless all or none of encodings have rids
  amendments.json
  webrtc.html
  webrtc.js
Labels: Editors can integrate, Needs Test, Simulcast

#2775 TypeError on duplicate rids
  amendments.json
  webrtc.html
Labels: Editors can integrate, Simulcast

#2758 Don't let offers to receive simulcast overwrite existing [[SendEncodings]]
  webrtc.html
Labels: Needs Test, Simulcast

#2785 Move RTCRtpEncodingParameters.maxFramerate to webrtc-pc
  amendments.json
  base-rec.html
  webrtc.html
  webrtc.js
Labels: Editors can integrate

#2773 add url attribute to RTCIceCandidate
  amendments.json
  base-rec.html
  webrtc.html
Labels: Needs Test
