Repository w3c/webrtc-pc, pull requests merged in 2023-04, with the labels that each got.

#2852 Update to ReSpec version 32.8.1
  base-rec.html
  respec-w3c-common.js
  webrtc.html
Labels: Editorial, repo-management

#2829 setParameters(), replaceTrack(), & insertDTMF() reject after stop().
  amendments.json
  base-rec.html
  webrtc.html
Labels: Editors can integrate

#2850 Add sender/receiver.getCapabilities() algorithms (and use them in offer/answer)
  webrtc.html
Labels: Editors can integrate, Editorial

#2854 Export links to addTransceiver/setParameters steps + unnumber some steps
  webrtc.html
Labels: Editorial

#2857 Export "list of implemented send codecs"
  webrtc.html
Labels: Editorial

#2864 Export [[ReceiverTrack]].
  webrtc.html
Labels: Editorial

#2862 Update to ReSpec version 34.0.1
  respec-w3c-common.js
Labels: Editorial, repo-management

#2863 Add a proper definition to the "DTMF playout task steps"
  webrtc.html
Labels: Editorial
