Repository w3c/webrtc-pc, pull requests merged in 2023-01, with the labels that each got.

#2809 Remove reference to removed test
  webrtc.html
Labels: Editorial

#2816 Update to ReSpec version 32.6.1
  respec-w3c-common.js
Labels: Editorial, repo-management

#2813 Ignore comma-separated rid alternatives.
  amendments.json
  webrtc.html
Labels: Editors can integrate, Simulcast

#2814 Update explanation of simulcast envelope.
  amendments.json
  webrtc.html
Labels: Editors can integrate, Simulcast
