Repository w3c/webrtc-pc, pull requests merged in 2023-05, with the labels that each got.

#2868 Update to ReSpec version 34.1.1
  respec-w3c-common.js
Labels: Editorial, repo-management

#2859 Fix connectionState to return [[ConnectionState]].
  webrtc.html
Labels: Editors can integrate, Editorial

#2870 Reorder RTCIceTransportState enum to match RTCIceConnectionState enum.
  webrtc.html
Labels: Editorial
