Repository w3c/webrtc-pc, pull requests merged in 2023-03, with the labels that each got.

#2833 Annotate amendment boxes
  amendments.js
  webrtc.css
Labels: Editorial

#2826 Add internal slots for signaling state, connection state, ice gatheri…
  amendments.js
  webrtc.html
Labels: Editors can integrate, Editorial

#2836 Fix scaleResolutionDownBy explanatory prose to match normative algorithm
  webrtc.html
Labels: Editorial

#2843 Mark PreferredCodec internal slot as exported
  webrtc.html
Labels: Editorial

#2828 Express RTCPeerConnectionState values using [[IceConnectionState]], and reduce complexity
  webrtc.html
Labels: Editors can integrate, Editorial

#2846 Update to ReSpec version 32.8.0
  respec-w3c-common.js
Labels: Editorial, repo-management

#2851 Export more definitions to use in webrtc-extensions
  webrtc.html
Labels: Editorial
