Repository w3c/webrtc-pc, pull requests merged in 2023-06, with the labels that each got.

#2872 editorial: export RTCRtpTransceiver "transceiver kind"
  webrtc.html
Labels: Editorial

#2877 Update to ReSpec version 34.1.2
  respec-w3c-common.js
Labels: Editorial, repo-management

#2875 Make removeTrack() a no-op after transceiver.stop()
  amendments.json
  base-rec.html
  webrtc.html
Labels: Editors can integrate

#2882 Update to ReSpec version 34.1.3
  respec-w3c-common.js
Labels: Editorial, repo-management

#2883 Update to ReSpec version 34.1.4
  respec-w3c-common.js
Labels: Editorial, repo-management

#2884 Clarify description of "checking" iceConnectionState
  webrtc.html
Labels: Editorial, Needs Test
