Repository w3c/webrtc-pc, pull requests merged in 2024-03, with the labels that each got.

#2946 Update to ReSpec version 34.5.0
  respec-w3c-common.js
Labels: Editorial, repo-management

#2910 Document test updates associated with amendments
  amendments.json
  amendments.md
  tools/check-rec-amendment.js
Labels: Editorial

#2948 Clarify when RTCIceCandidate's relayProtocol and url members are null.
  webrtc.html
Labels: Editorial

#2951 Make RTCIceCandidatePair members required
  webrtc.html
Labels: Editorial

#2894 Queue two tasks upon finishing ICE gathering, and fire gatheringstatechange & icegatheringstatechange in same task
  amendments.json
  base-rec.html
  webrtc.html
Labels: Editors can integrate
