Repository w3c/webrtc-pc, pull requests merged in 2024-02, with the labels that each got.

#2934 Update to ReSpec version 34.4.0
  respec-w3c-common.js
Labels: Editorial, repo-management

#2928 add test coverage annotation for sdp munging
  webrtc.html
Labels: Editorial

#2941 remove setCodecPreferences note already covered by JSEP
  webrtc.html
Labels: Editorial

#2935 Redefine SendCodecs and ReceiveCodecs
  amendments.json
  base-rec.html
  webrtc.html
Labels: Editors can integrate
