Repository w3c/webrtc-pc, pull requests merged in 2025-07, with the labels that each got.

#3059 Update to ReSpec version 35.4.2
  respec-w3c-common.js
Labels: Editorial, repo-management

#3067 Remove duplicate word
  webrtc.html
Labels: Editorial

#3068 Prevent GC of non-closed RTCDataChannels in workers
  amendments.json
  base-rec.html
  webrtc.html
Labels: Editors can integrate
